version: "3.9"
services:
  web-ch:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=dbagency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db-ch
  db-ch:
    image: postgres:14
    volumes:
      - postgres_agency:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dbagency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_agency: